#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-pr-check

on: 
  push:
    branches:
      - s390x-test

jobs:
#  build:
#    runs-on: ubuntu-20.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Cache local Maven repository
#      uses: actions/cache@v2
#      with:
#       path: ~/.m2/repository
#       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#       restore-keys: |
#        ${{ runner.os }}-maven-      
#    - name: Set up JDK 11
#      uses: actions/setup-java@v1
#      with:
#        java-version: 11
#    - name: Build with Maven
#      run: mvn -B clean install -U -Pintegration

  build-on-z:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Enable running multiple architectures
      run: |
        sudo docker run --rm --privileged linuxkit/binfmt:4ea3b9b0938cbd19834c096aa31ff475cc75d281
    - name: Run build 
      uses: uraimo/run-on-arch-action@v2.0.9
      with:
        arch: s390x
        distro: ubuntu20.04
        run: | 
         apt-get update && apt-get install -y wget curl binutils* 
         mkdir -p /opt/adoptj9/java
         ls /opt/adoptj9
         curl -SL -o adoptjdk.tar.gz https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.2%2B10_openj9-0.15.1/OpenJDK12U-jdk_s390x_linux_openj9_12.0.2_10_openj9-0.15.1.tar.gz
         tar -zxf adoptjdk.tar.gz -C /opt/adoptj9/java --strip-components 1
         echo "tar complete"
         ls /opt/adoptj9/java
         ls /opt/adoptj9/java/bin
         export JAVA_HOME=/opt/adoptj9/java
         export PATH=$JAVA_HOME/bin:$PATH
         java -version
         wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.tar.gz 
         tar -xzf apache-maven-3.6.3-bin.tar.gz  
         export PATH=`pwd`/apache-maven-3.6.3/bin/:$PATH  
         mvn -v 
         export MAVEN_OPTS=-Xmx2g
         export _JAVA_OPTIONS="-Xjit:disableMccFreeBlockRecycling  -Xms256m -Xmx512m"
         mvn -B -X -e clean install -U -Pintegration
    
